server:
    port: 8888
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:18761/eureka/

spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/qsb61990a/SpringcloudConfig.git
                    searchPaths: /respo
                    username:
                    password:
    application:
        name: config-server