eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:18761/eureka/

server:
  port: 18764
spring:
  application:
    name: service-feign

#datasource config
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/goule?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
  username: root
  password: root

#mybatis config
mybatis:
  typeAliasesPackage: com.example.servicefeign.model
  mapperLocations: classpath:mapper/*.xml